# run_config.yaml

## 현재 회사문서 -> 병원기록 -> ㄱㅖㅇㅑㄱㅅㅓ 돌리는중

model:
  model_name: "klue/roberta-base"
  pii_state_dir: # 없는 경우 null, 있는 경우 리스트로 쓰기
    - "/home/student1/Pipeline-for-Personal-Confidential-Information-Detection/checkpoints/experiment_test_40_01/epoch2_model.pt"

exp:
  is_pii: False  # 개인정보모델 학습이면 True, 기밀정보모델 학습이면 False
  name: "test_42"  # "실험버전_실험순번" 
  batch_size: 32
  num_epochs: 10
  learning_rate: 1e-5
  device: "cuda:1"  # "cpu" or "cuda:0" or "cuda:1"
  sampling_ratio: 10000.0 # 데이터 불균형 처리 비율
  k_fold: 1
  generation_num: 5 # [test] 문맥 문장 데이터 생성 시 생성할 샘플의 수
  z_score_threshold: 1.5

data:
  train_data_dir: "/home/student1/Pipeline-for-Personal-Confidential-Information-Detection/data/08_contract_data/fold_01"  # 학습데이터가 들어있는 directory
  valid_data_dir: "/home/student1/Pipeline-for-Personal-Confidential-Information-Detection/data/08_contract_data/fold_02"

label_mapping:
  pii_label_2_id:
    일반정보: 0
    준식별자: 1
    개인정보: 2
  pii_id_2_label:
    0: "일반정보"
    1: "준식별자"
    2: "개인정보"
  confid_label_2_id:
    일반정보 : 0
    기밀정보 : 1
  confid_id_2_label:
    0: "일반정보"
    1: "기밀정보"

db:
  host: "127.0.0.1"
  port: "55432"
  dbname: "postgres"
  user: "student1"
  password: "onestone"

api_key:
  label_studio: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6ODA2NzQ2MjgzMywiaWF0IjoxNzYwMjYyODMzLCJqdGkiOiI1ZTg3MjYxZTIyMDY0Y2FkODYxZjA3Yzk1YjUxM2M4YyIsInVzZXJfaWQiOiIxIn0.fZJKc8_yZA09uHDKqIreTy1VtFTkFLIVVj6QFjwbjjc"

dictionary_init:
  domain_ids: # 반드시 리스트로 작성할것
    - "8"
  answer_sheet_dir: # 없는 경우 null, 있는 경우 "domain_id": "dir"
    "8": "/home/student1/Pipeline-for-Personal-Confidential-Information-Detection/data/08_contract_data/answer_sheet.csv"

  raw_data_based_dictionary_init_data_dir: # 없는 경우 null, 있는 경우 "domain_id": "dir"
    null